In [2]:
import numpy as np

In [3]:
x = np.array([[0, 3, 6], [4, 2, 1], [5, 10, 7]])
print(x)

[[ 0  3  6]
 [ 4  2  1]
 [ 5 10  7]]


## Sort by row

### ascending

In [6]:
ind = x[:,2].argsort()
print(x[ind,:])

[[ 4  2  1]
 [ 0  3  6]
 [ 5 10  7]]


### descending

In [7]:
ind = x[:,2].argsort()[::-1]
print(x[ind,:])

[[ 5 10  7]
 [ 0  3  6]
 [ 4  2  1]]


## Sort by column

### ascending

In [8]:
ind = x[2,:].argsort()
print(x[:,ind])

[[ 0  6  3]
 [ 4  1  2]
 [ 5  7 10]]


### descending

In [9]:
ind = x[2,:].argsort()[::-1]
print(x[:,ind])

[[ 3  6  0]
 [ 2  1  4]
 [10  7  5]]
